name: CI

on: [push]

jobs:
  abaplint:
    name: abaplint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Run abaplint
        run: |
          npm -g install @abaplint/cli
          abaplint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
