# This is a basic workflow to help you get started with Actions

name: Run abaplint
on: [pull_request]

jobs:
  abaplint:
    name: abaplint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Run abaplint
        run: |
          npm -g install @abaplint/cli
          abaplint
